title: "Target E-Commerce Revenue Analysis"
description: "A project analyzing e-commerce revenue."
theme: minima # Optional, if you're using a Jekyll theme
baseurl: ""  # No subdirectory for local testing
url: "http://localhost:4000"
markdown: kramdown
permalink: pretty # Optional: pretty URLs for pages
plugins:
  - jekyll-feed # Optional: Adds RSS feed functionality (useful if hosting)
  - jekyll-sitemap # Optional: Automatically generates a sitemap
